### ISSUE TITLE
Text Size and Visible Count?

### ISSUE THREAD

**Issue by VeeraAndroid** [Farhad2015/Custom-Year-Picker#1]
How to change text size, and increase visible item count 3 to 5.

**Comment by Farhad2015** [comment]
_**for text size add this code in style:**_ 
<style name="NumberPickerText">
    <item name="android:textSize">40dp</item>
</style>
**then add this code in backend:** 
ContextThemeWrapper cw = new ContextThemeWrapper(this, R.style.NumberPickerText);
    NumberPicker np = new NumberPicker(cw);

**_For visible item: if you want to visible item 3 to 5, you need to use listview._**
